"use client";
import { useEffect, useState } from "react";
import { Activity, ClipboardList, Loader2, ShieldAlert, X } from "lucide-react";

type Permission=string;
type Health={metrics:{newUsers:number;published:number;offers:number;acceptanceRate:number;offerCoverage:number;noOffer:number;activeSellers:number;openCases:number;failedBilling:number};categoryGaps:{categoryId:string;categoryName:string;requests:number;offers:number;gap:number}[]};
type Case={id:string;subjectType:string;subjectId:string;category:string;summary:string;priority:string;status:string;createdAt:string;assignee:{name:string|null;email:string|null}|null};
type Audit={id:string;action:string;reason:string;createdAt:string;actor:{name:string|null;email:string|null};targetUser:{name:string|null;email:string|null;membershipNumber:string}|null};

export function AdminOperationsCenter({permissions}:{permissions:Permission[]}){const canModerate=permissions.includes("moderation.view"),canAudit=permissions.includes("audit.view"),canHealth=permissions.includes("analytics.view");const [tab,setTab]=useState<"health"|"moderation"|"audit">(canHealth?"health":canModerate?"moderation":"audit");const [health,setHealth]=useState<Health|null>(null);const [cases,setCases]=useState<Case[]>([]);const [audits,setAudits]=useState<Audit[]>([]);const [busy,setBusy]=useState(false);
useEffect(()=>{let stale=false;setBusy(true);const endpoint=tab==="health"?"/api/admin/health":tab==="moderation"?"/api/admin/moderation":"/api/admin/audit";fetch(endpoint).then(r=>r.json()).then(data=>{if(stale)return;if(tab==="health")setHealth(data);else if(tab==="moderation")setCases(data.items??[]);else setAudits(data.items??[])}).finally(()=>!stale&&setBusy(false));return()=>{stale=true}},[tab]);
return <section className="mt-8 overflow-hidden rounded-[26px] border border-white/10 bg-white/[.045]"><div className="flex flex-wrap gap-2 border-b border-white/10 p-4">{canHealth&&<Nav active={tab==="health"} onClick={()=>setTab("health")} icon={Activity}>Marketplace sağlığı</Nav>}{canModerate&&<Nav active={tab==="moderation"} onClick={()=>setTab("moderation")} icon={ShieldAlert}>Moderasyon</Nav>}{canAudit&&<Nav active={tab==="audit"} onClick={()=>setTab("audit")} icon={ClipboardList}>Denetim kayıtları</Nav>}</div><div className="p-6">{busy?<div className="flex justify-center py-16"><Loader2 className="h-7 w-7 animate-spin text-emerald-300"/></div>:tab==="health"&&health?<HealthView data={health}/>:tab==="moderation"?<ModerationView items={cases} canManage={permissions.includes("moderation.manage")} onUpdated={()=>setTab("health")}/>:<AuditView items={audits}/>}</div></section>}
function Nav({active,onClick,icon:Icon,children}:{active:boolean;onClick:()=>void;icon:typeof Activity;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm ${active?"bg-emerald-300 font-semibold text-[#071310]":"text-white/50 hover:bg-white/[.05]"}`}><Icon className="h-4 w-4"/>{children}</button>}
function HealthView({data}:{data:Health}){const m=data.metrics;const cards=[["Yeni kullanıcı",m.newUsers],["Yayınlanan talep",m.published],["Teklif",m.offers],["Kabul oranı",`%${m.acceptanceRate}`],["Teklif kapsaması",`%${m.offerCoverage}`],["Teklifsiz talep",m.noOffer],["Aktif satıcı",m.activeSellers],["Açık vaka",m.openCases],["Başarısız ödeme",m.failedBilling]];return <><div><p className="text-xs uppercase tracking-[.18em] text-emerald-300/60">Son 30 gün</p><h3 className="mt-1 text-xl font-semibold">Marketplace sağlık merkezi</h3></div><div className="mt-5 grid gap-3 sm:grid-cols-3 xl:grid-cols-5">{cards.map(([k,v])=><div key={String(k)} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><p className="text-xs text-white/35">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div><h4 className="mt-7 font-semibold">Arz-talep boşluğu yüksek kategoriler</h4><div className="mt-3 space-y-2">{data.categoryGaps.map(x=><div key={x.categoryId} className="grid grid-cols-[1fr_auto_auto_auto] gap-4 rounded-xl bg-white/[.035] px-4 py-3 text-sm"><span><strong className="block font-semibold text-white/90">{x.categoryName}</strong><small className="mt-1 block font-mono text-[11px] text-white/35">{x.categoryId}</small></span><span className="text-white/45">{x.requests} talep</span><span className="text-white/45">{x.offers} teklif</span><span className="font-semibold text-amber-300">Açık {x.gap}</span></div>)}</div></>}
function ModerationView({items,canManage,onUpdated}:{items:Case[];canManage:boolean;onUpdated:()=>void}){
  const [pending,setPending]=useState<{item:Case;status:string}|null>(null);
  const [note,setNote]=useState("");
  const [busy,setBusy]=useState(false);
  async function update(){if(!pending||note.trim().length<5)return;setBusy(true);try{const r=await fetch("/api/admin/moderation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:pending.item.id,status:pending.status,priority:pending.item.priority,resolutionNote:note.trim()})});if(r.ok){setPending(null);setNote("");onUpdated();}}finally{setBusy(false);}}
  function requestUpdate(item:Case,status:string){setPending({item,status});setNote("");}
  return <><h3 className="text-xl font-semibold">Moderasyon kuyruğu</h3><div className="mt-5 space-y-3">{items.length?items.map(x=><div key={x.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-white/35">{x.subjectType} · {x.subjectId}</p><p className="mt-1 font-semibold">{x.category}</p><p className="mt-2 text-sm text-white/55">{x.summary}</p></div><div className="text-right"><span className="rounded-full bg-amber-300/10 px-2.5 py-1 text-xs text-amber-200">{x.priority}</span><p className="mt-2 text-xs text-white/40">{x.status}</p></div></div>{canManage&&!["RESOLVED","DISMISSED"].includes(x.status)?<div className="mt-4 flex gap-2"><button onClick={()=>requestUpdate(x,"INVESTIGATING")} className="rounded-xl border border-white/10 px-3 py-2 text-xs">İncelemede</button><button onClick={()=>requestUpdate(x,"RESOLVED")} className="rounded-xl bg-emerald-300 px-3 py-2 text-xs font-bold text-[#071310]">Çözüldü</button><button onClick={()=>requestUpdate(x,"DISMISSED")} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Kapat</button></div>:null}</div>):<p className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">Açık moderasyon kaydı yok.</p>}</div>{pending?<div className="fixed inset-0 z-[220] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.currentTarget===event.target)setPending(null);}}><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#0b1d19] p-6"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-amber-300/60">Moderasyon işlemi</p><h4 className="mt-2 text-xl font-semibold">Gerekçe ve çözüm notu</h4><p className="mt-2 text-sm text-white/45">Yeni durum: {pending.status}</p></div><button onClick={()=>setPending(null)} className="rounded-xl border border-white/10 p-2"><X className="h-4 w-4"/></button></div><textarea autoFocus rows={4} value={note} onChange={event=>setNote(event.target.value)} placeholder="İnceleme sonucunu veya işlem gerekçesini yazın" className="mt-5 w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 text-sm outline-none placeholder:text-white/25 focus:border-emerald-300/40"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setPending(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/60">Vazgeç</button><button disabled={busy||note.trim().length<5} onClick={()=>void update()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-4 py-2.5 text-sm font-bold text-[#071310] disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:null}Kaydet</button></div></div></div>:null}</>}
function AuditView({items}:{items:Audit[]}){return <><h3 className="text-xl font-semibold">Değiştirilemez denetim kayıtları</h3><div className="mt-5 space-y-2">{items.map(x=><div key={x.id} className="grid gap-2 rounded-2xl border border-white/[.07] bg-black/15 p-4 sm:grid-cols-[180px_1fr_180px]"><div><p className="text-xs font-semibold text-emerald-200">{x.action}</p><p className="mt-1 text-[11px] text-white/35">{new Date(x.createdAt).toLocaleString("tr-TR")}</p></div><div><p className="text-sm">{x.reason}</p><p className="mt-1 text-xs text-white/35">Hedef: {x.targetUser?.name??x.targetUser?.email??"Sistem"}</p></div><p className="text-xs text-white/45 sm:text-right">{x.actor.name??x.actor.email}</p></div>)}</div></>}
