"use client";

import { Check, ChevronLeft, ChevronRight, Clock3, FileText, HandCoins, Loader2, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { useState } from "react";
import { ExportCsvButton } from "@/components/admin/ExportCsvButton";

type AdminUser = { id:string; name:string|null; email:string|null; membershipNumber:string; status:"ACTIVE"|"SUSPENDED"|"DELETED"; platformRole:"USER"|"SUPPORT"|"MODERATOR"|"ANALYST"|"ADMIN"|"SUPER_ADMIN"; planTier:"STANDARD"|"PREMIUM"|"PROFESSIONAL"|"CORPORATE"|null; bonusOfferCredits:number; createdAt:string; lastLoginAt:string|null; isAdmin:boolean; _count?:{createdRequests:number;submittedOffers:number} };
type TimelineItem={id:string;type:string;title:string;occurredAt:string;meta?:string};
type UserDetail = AdminUser & { phone:string|null; country:string; city:string|null; district:string|null; biography:string|null; updatedAt:string; emailVerified:string|null; accounts:{provider:string}[]; _count:{createdRequests:number;submittedOffers:number}; createdRequests:{id:string;title:string;status:string;offerCount:number;createdAt:string}[]; submittedOffers:{id:string;title:string|null;status:string;amount:string;currency:string;createdAt:string;request:{id:string;title:string}}[]; timeline:TimelineItem[] };

const dateTime = (value:string|null) => value ? new Intl.DateTimeFormat("tr-TR", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "Henüz giriş yapmadı";

export function AdminUsersTable({ initialUsers, permissions }: { initialUsers: AdminUser[]; permissions: string[] }) {
  const [users,setUsers]=useState(initialUsers); const [busyId,setBusyId]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [detail,setDetail]=useState<UserDetail|null>(null); const [detailBusy,setDetailBusy]=useState(false); const [tab,setTab]=useState<"info"|"history">("info"); const [query,setQuery]=useState(""); const [status,setStatus]=useState(""); const [role,setRole]=useState(""); const [plan,setPlan]=useState(""); const [page,setPage]=useState(1); const [totalPages,setTotalPages]=useState(1); const [pendingSave,setPendingSave]=useState<AdminUser|null>(null); const [reason,setReason]=useState("");
  const canSeeSensitive=permissions.includes("sensitive.view"); const canManageUsers=permissions.includes("users.manage"); const canManageRoles=permissions.includes("roles.manage"); const canManageBilling=permissions.includes("billing.manage");
  function update(id:string,patch:Partial<AdminUser>){setUsers(v=>v.map(u=>u.id===id?{...u,...patch}:u));}
  async function save(user:AdminUser,saveReason:string){setBusyId(user.id);setMessage(null);try{const payload={userId:user.id,reason:saveReason,...(canManageUsers?{status:user.status}:{}),...(canManageRoles?{platformRole:user.platformRole}:{}),...(canManageBilling?{planTier:user.planTier??"STANDARD",bonusOfferCredits:user.bonusOfferCredits}:{})};const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {message?:string};setMessage(data.message??"İşlem tamamlandı.");if(response.ok)update(user.id,{isAdmin:user.platformRole!=="USER"});}finally{setBusyId(null);}}
  async function inspect(id:string){setDetailBusy(true);setDetail(null);setTab("info");try{const response=await fetch(`/api/admin/users/${id}`);const data=await response.json() as {user?:UserDetail;message?:string};if(response.ok&&data.user)setDetail({...data.user,isAdmin:data.user.platformRole!=="USER"});else setMessage(data.message??"Bilgiler alınamadı.");}finally{setDetailBusy(false);}}
  async function search(nextPage=1){setBusyId("search");try{const p=new URLSearchParams({page:String(nextPage),pageSize:"20"});if(query.trim())p.set("q",query.trim());if(status)p.set("status",status);if(role)p.set("role",role);if(plan)p.set("plan",plan);const response=await fetch(`/api/admin/users?${p}`);const data=await response.json() as {users?:AdminUser[];pagination?:{page:number;totalPages:number};message?:string};if(response.ok&&data.users){setUsers(data.users);setPage(data.pagination?.page??1);setTotalPages(data.pagination?.totalPages??1)}else setMessage(data.message??"Arama başarısız.");}finally{setBusyId(null)}}
  return <>
    <section className="overflow-hidden rounded-[26px] border border-white/10 bg-white/[0.045] shadow-2xl shadow-black/20">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-300/60">Üyelik yönetimi</p><h2 className="mt-1 text-xl font-semibold">Kullanıcılar ve yetkiler</h2><p className="mt-1 text-xs text-white/35">Listelenen kullanıcıları CSV olarak indirebilirsin.</p></div><div className="flex items-center gap-3">{message&&<p className="rounded-full bg-emerald-300/10 px-3 py-1.5 text-xs text-emerald-200">{message}</p>}<ExportCsvButton filename="talepo-kullanicilar.csv" rows={users.map(user=>({"Ad soyad":user.name??"", "E-posta":user.email??"", "Üyelik no":user.membershipNumber, "Yetki":user.platformRole, "Plan":user.planTier??"", "Durum":user.status, "Son giriş":user.lastLoginAt??"", "Kayıt zamanı":user.createdAt}))}/></div></div>
      <div className="grid gap-2 border-b border-white/10 p-4 sm:grid-cols-[1fr_repeat(3,150px)_auto]"><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/15 px-3"><Search className="h-4 w-4 text-white/30"/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void search(1)}} placeholder={canSeeSensitive?"İsim, e-posta, telefon veya üye no":"İsim veya üye no"} className="w-full bg-transparent py-2.5 text-sm outline-none"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#102421] px-3 text-xs"><option value="">Tüm durumlar</option><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Pasif</option></select><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-white/10 bg-[#102421] px-3 text-xs"><option value="">Tüm roller</option><option value="USER">Kullanıcı</option><option value="SUPPORT">Destek</option><option value="MODERATOR">Moderatör</option><option value="ANALYST">Analist</option><option value="ADMIN">Admin</option>{canManageRoles?<option value="SUPER_ADMIN">Süper Admin</option>:null}</select>{canManageBilling?<select value={plan} onChange={e=>setPlan(e.target.value)} className="rounded-xl border border-white/10 bg-[#102421] px-3 text-xs"><option value="">Tüm planlar</option><option value="STANDARD">Bireysel</option><option value="PROFESSIONAL">Profesyonel</option></select>:<div className="flex items-center rounded-xl border border-white/10 bg-black/10 px-3 text-xs text-white/30">Plan bilgisi gizli</div>}<button onClick={()=>void search(1)} className="rounded-xl bg-emerald-300 px-4 py-2.5 text-xs font-bold text-[#071310]">Ara</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-black/15 text-[11px] uppercase tracking-[.12em] text-white/35"><tr>{["Kullanıcı","Yetki","Plan","Durum","Son giriş","Bonus","İşlem"].map(x=><th key={x} className="px-4 py-4 font-semibold first:pl-6">{x}</th>)}</tr></thead><tbody className="divide-y divide-white/[.07]">{users.map(user=><tr key={user.id} className="hover:bg-white/[.035]">
        <td className="px-6 py-4"><button disabled={!canSeeSensitive} onClick={canSeeSensitive?()=>void inspect(user.id):undefined} className="flex items-center gap-3 text-left disabled:cursor-default"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-300/10 font-semibold text-emerald-200">{(user.name??user.email??"K")[0].toUpperCase()}</span><span><span className="flex items-center gap-2 font-semibold">{user.name??"İsimsiz kullanıcı"}{user.isAdmin&&<ShieldCheck className="h-4 w-4 text-amber-300"/>}</span><span className="mt-0.5 block text-xs text-white/40">{user.email} · {user.membershipNumber}</span></span></button></td>
        <td className="px-4">{canManageRoles?<select value={user.platformRole} onChange={e=>update(user.id,{platformRole:e.target.value as AdminUser["platformRole"]})} className="rounded-xl border border-white/10 bg-[#102421] px-3 py-2 text-xs"><option value="USER">Kullanıcı</option><option value="SUPPORT">Destek</option><option value="MODERATOR">Moderatör</option><option value="ANALYST">Analist</option><option value="ADMIN">Admin</option><option value="SUPER_ADMIN">Süper Admin</option></select>:<span className="text-xs text-white/50">{roleLabel(user.platformRole)}</span>}</td>
        <td className="px-4">{canManageBilling?<select value={user.planTier??"STANDARD"} onChange={e=>update(user.id,{planTier:e.target.value as NonNullable<AdminUser["planTier"]>})} className="rounded-xl border border-white/10 bg-[#102421] px-3 py-2 text-xs"><option value="STANDARD">Bireysel</option><option value="PROFESSIONAL">Profesyonel</option></select>:<span className="text-xs text-white/35">Gizli</span>}</td>
        <td className="px-4">{canManageUsers&&(canManageRoles||user.platformRole==="USER")?<select value={user.status} onChange={e=>update(user.id,{status:e.target.value as AdminUser["status"]})} className="rounded-xl border border-white/10 bg-[#102421] px-3 py-2 text-xs"><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Pasif</option></select>:<span className="text-xs text-white/50">{user.status==="ACTIVE"?"Aktif":"Pasif"}</span>}</td>
        <td className="px-4 text-xs text-white/50">{canSeeSensitive?dateTime(user.lastLoginAt):"Gizli"}</td><td className="px-4">{canManageBilling?<input type="number" min={0} max={10000} value={user.bonusOfferCredits} onChange={e=>update(user.id,{bonusOfferCredits:Number(e.target.value)})} className="w-20 rounded-xl border border-white/10 bg-[#102421] px-3 py-2"/>:<span className="text-xs text-white/35">Gizli</span>}</td>
        <td className="px-4"><div className="flex gap-2">{canSeeSensitive?<button onClick={()=>void inspect(user.id)} className="rounded-xl border border-white/10 px-3 py-2 text-xs">İncele</button>:null}{canManageUsers&&(canManageRoles||user.platformRole==="USER")?<button onClick={()=>{setPendingSave(user);setReason("");}} disabled={busyId===user.id} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-3 py-2 text-xs font-bold text-[#071310]">{busyId===user.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}Kaydet</button>:<span className="text-xs text-white/30">Salt okunur</span>}</div></td>
      </tr>)}</tbody></table></div>
      <div className="flex items-center justify-end gap-3 border-t border-white/10 px-5 py-4"><button disabled={page<=1} onClick={()=>void search(page-1)} className="rounded-xl border border-white/10 p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4"/></button><span className="text-xs text-white/45">Sayfa {page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>void search(page+1)} className="rounded-xl border border-white/10 p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4"/></button></div>
    </section>
    {(detailBusy||detail)&&<div className="fixed inset-0 z-[100] flex justify-end bg-black/60 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target){setDetail(null);setDetailBusy(false);}}}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-[#091915] p-6 shadow-2xl">{detailBusy?<div className="flex h-full items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-emerald-300"/></div>:detail&&<><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-emerald-300/60">Kullanıcı dosyası</p><h3 className="mt-2 text-2xl font-semibold">{detail.name??"İsimsiz kullanıcı"}</h3><p className="mt-1 text-sm text-white/45">{detail.email} · {detail.membershipNumber}</p></div><button onClick={()=>setDetail(null)} className="rounded-xl border border-white/10 p-2"><X className="h-5 w-5"/></button></div>
      <div className="mt-6 grid grid-cols-3 gap-3"><Stat icon={Clock3} label="Son giriş" value={dateTime(detail.lastLoginAt)}/><Stat icon={FileText} label="Talepler" value={String(detail._count.createdRequests)}/><Stat icon={HandCoins} label="Teklifler" value={String(detail._count.submittedOffers)}/></div>
      <div className="mt-6 flex gap-2 border-b border-white/10"><Tab active={tab==="info"} onClick={()=>setTab("info")}>Kayıt bilgileri</Tab><Tab active={tab==="history"} onClick={()=>setTab("history")}>Geçmiş hareketler</Tab></div>
      {tab==="info"?<div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Ad soyad",detail.name],["E-posta",detail.email],["Telefon",detail.phone],["Konum",[detail.district,detail.city,detail.country].filter(Boolean).join(", ")],["Kayıt yöntemi",detail.accounts.map(x=>x.provider).join(", ")||"Şifre"],["Kayıt zamanı",dateTime(detail.createdAt)],["E-posta doğrulama",dateTime(detail.emailVerified)],["Son güncelleme",dateTime(detail.updatedAt)]].map(([k,v])=><div key={k as string} className="rounded-2xl border border-white/[.07] bg-white/[.035] p-4"><p className="text-xs text-white/35">{k}</p><p className="mt-1 text-sm">{v||"Belirtilmemiş"}</p></div>)}{detail.biography&&<div className="sm:col-span-2 rounded-2xl border border-white/[.07] bg-white/[.035] p-4"><p className="text-xs text-white/35">Biyografi</p><p className="mt-2 text-sm leading-6">{detail.biography}</p></div>}</div>:<div className="mt-5 space-y-3"><div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[.06] p-4"><p className="text-xs text-emerald-200/60">Son giriş zamanı</p><p className="mt-1 font-semibold text-emerald-100">{dateTime(detail.lastLoginAt)}</p></div>{detail.timeline?.map(item=><div key={item.id} className="relative ml-3 border-l border-white/10 py-2 pl-6 before:absolute before:-left-1 before:top-5 before:h-2 before:w-2 before:rounded-full before:bg-emerald-300"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-200/55">{item.type}</p><p className="mt-1 text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-white/35">{dateTime(item.occurredAt)}{item.meta?` · ${item.meta}`:""}</p></div>)}</div>}
      </>}</aside></div>}
    {pendingSave?<div className="fixed inset-0 z-[210] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.currentTarget===event.target)setPendingSave(null);}}><div role="dialog" aria-modal="true" aria-labelledby="admin-change-title" className="w-full max-w-lg rounded-[26px] border border-white/10 bg-[#0b1d19] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-300/60">Denetimli işlem</p><h3 id="admin-change-title" className="mt-2 text-xl font-semibold">Değişiklik gerekçesi</h3><p className="mt-2 text-sm text-white/45">{pendingSave.name??pendingSave.email} için yapılan işlem kalıcı denetim kaydına eklenecek.</p></div><button type="button" onClick={()=>setPendingSave(null)} className="rounded-xl border border-white/10 p-2"><X className="h-4 w-4"/></button></div><textarea autoFocus value={reason} onChange={event=>setReason(event.target.value)} placeholder="Örn. Destek talebi doğrultusunda plan güncellendi" rows={4} className="mt-5 w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 text-sm text-white outline-none placeholder:text-white/25 focus:border-emerald-300/40"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setPendingSave(null)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white/60">Vazgeç</button><button type="button" disabled={reason.trim().length<5} onClick={()=>{const target=pendingSave;const submittedReason=reason.trim();setPendingSave(null);void save(target,submittedReason);}} className="rounded-xl bg-emerald-300 px-4 py-2.5 text-sm font-bold text-[#071310] disabled:opacity-40">Kaydet ve kayıt oluştur</button></div></div></div>:null}
  </>;
}
function Stat({icon:Icon,label,value}:{icon:typeof UserRound;label:string;value:string}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.035] p-4"><Icon className="h-4 w-4 text-emerald-300"/><p className="mt-3 text-[11px] text-white/35">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`border-b-2 px-3 py-3 text-sm ${active?"border-emerald-300 text-emerald-200":"border-transparent text-white/40"}`}>{children}</button>}
function roleLabel(role:AdminUser["platformRole"]){return {USER:"Kullanıcı",SUPPORT:"Destek",MODERATOR:"Moderatör",ANALYST:"Analist",ADMIN:"Admin",SUPER_ADMIN:"Süper Admin"}[role]}
