"use client";

import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, FileText, HandCoins, Loader2, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { useState } from "react";
import { ExportCsvButton } from "@/components/admin/ExportCsvButton";
import { RoleUserNotesPanel } from "@/components/admin/RoleUserNotesPanel";
import { SuperAdminMfaReset } from "@/components/admin/SuperAdminMfaReset";

type AdminUser = { id:string; name:string|null; email:string|null; membershipNumber:string; status:"ACTIVE"|"SUSPENDED"|"DELETED"; platformRole:"USER"|"SUPPORT"|"MODERATOR"|"ANALYST"|"ADMIN"|"SUPER_ADMIN"; planTier:"STANDARD"|"PREMIUM"|"PROFESSIONAL"|"CORPORATE"|null; billingStatus:string|null; billingPeriodEnd:string|null; bonusOfferCredits:number; createdAt:string; lastLoginAt:string|null; isAdmin:boolean; _count?:{createdRequests:number;submittedOffers:number} };
type TimelineItem={id:string;type:string;title:string;occurredAt:string;meta?:string};
type UserDetail = AdminUser & { phone:string|null; country:string; city:string|null; district:string|null; biography:string|null; updatedAt:string; emailVerified:string|null; accounts:{provider:string}[]; _count:{createdRequests:number;submittedOffers:number}; createdRequests:{id:string;title:string;status:string;offerCount:number;createdAt:string}[]; submittedOffers:{id:string;title:string|null;status:string;amount:string;currency:string;createdAt:string;request:{id:string;title:string}}[]; timeline:TimelineItem[] };

const dateTime = (value:string|null) => value ? new Intl.DateTimeFormat("tr-TR", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "Henüz giriş yapmadı";

export function AdminUsersTable({ initialUsers, permissions, currentUserId }: { initialUsers: AdminUser[]; permissions: string[]; currentUserId: string }) {
  const [users,setUsers]=useState(initialUsers); const [membershipOpen,setMembershipOpen]=useState(true); const [busyId,setBusyId]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [detail,setDetail]=useState<UserDetail|null>(null); const [detailBusy,setDetailBusy]=useState(false); const [tab,setTab]=useState<"info"|"history">("info"); const [query,setQuery]=useState(""); const [status,setStatus]=useState(""); const [role,setRole]=useState(""); const [plan,setPlan]=useState(""); const [page,setPage]=useState(1); const [totalPages,setTotalPages]=useState(1); const [pendingSave,setPendingSave]=useState<AdminUser|null>(null); const [reason,setReason]=useState(""); const [notedUser,setNotedUser]=useState<AdminUser|null>(null); const [mfaResetUser,setMfaResetUser]=useState<AdminUser|null>(null);
  const canSeeSensitive=permissions.includes("sensitive.view"); const canManageUsers=permissions.includes("users.manage"); const canManageRoles=permissions.includes("roles.manage"); const canManageLimitedRoles=permissions.includes("roles.manage.limited"); const canManageBilling=permissions.includes("billing.manage"); const canViewBilling=permissions.includes("billing.view")||canManageBilling;
  const canEditRole=(user:AdminUser)=>canManageRoles||canManageLimitedRoles&&user.platformRole!=="ADMIN"&&user.platformRole!=="SUPER_ADMIN";
  const canManageRoleNotes=(user:AdminUser)=>user.platformRole!=="USER"&&(canManageRoles||canManageLimitedRoles&&user.platformRole!=="ADMIN"&&user.platformRole!=="SUPER_ADMIN");
  function update(id:string,patch:Partial<AdminUser>){setUsers(v=>v.map(u=>u.id===id?{...u,...patch}:u));}
  async function save(user:AdminUser,saveReason:string){setBusyId(user.id);setMessage(null);try{const payload={userId:user.id,reason:saveReason,...(canManageUsers?{status:user.status}:{}),...(canEditRole(user)?{platformRole:user.platformRole}:{}),...(canManageBilling?{planTier:user.planTier??"STANDARD",bonusOfferCredits:user.bonusOfferCredits}:{})};const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {message?:string};setMessage(data.message??"İşlem tamamlandı.");if(response.ok)update(user.id,{isAdmin:user.platformRole!=="USER"});}finally{setBusyId(null);}}
  async function inspect(id:string){setDetailBusy(true);setDetail(null);setTab("info");try{const response=await fetch(`/api/admin/users/${id}`);const data=await response.json() as {user?:UserDetail;message?:string};if(response.ok&&data.user)setDetail({...data.user,isAdmin:data.user.platformRole!=="USER"});else setMessage(data.message??"Bilgiler alınamadı.");}finally{setDetailBusy(false);}}
  async function search(nextPage=1){setBusyId("search");try{const p=new URLSearchParams({page:String(nextPage),pageSize:"20"});if(query.trim())p.set("q",query.trim());if(status)p.set("status",status);if(role)p.set("role",role);if(plan)p.set("plan",plan);const response=await fetch(`/api/admin/users?${p}`);const data=await response.json() as {users?:AdminUser[];pagination?:{page:number;totalPages:number};message?:string};if(response.ok&&data.users){setUsers(data.users);setPage(data.pagination?.page??1);setTotalPages(data.pagination?.totalPages??1)}else setMessage(data.message??"Arama başarısız.");}finally{setBusyId(null)}}
  return <>
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-5"><button type="button" onClick={()=>setMembershipOpen((value)=>!value)} aria-expanded={membershipOpen} className="group flex min-w-0 flex-1 cursor-pointer items-center justify-between gap-4 text-left"><span><span className="block text-xs font-semibold uppercase tracking-[.18em] text-primary">Üyelik yönetimi</span><span className="mt-1 block text-xl font-semibold text-foreground">Kullanıcılar ve yetkiler</span><span className="mt-1 block text-xs text-muted-foreground">Kullanıcı listesi, yetkiler ve üyelik işlemleri</span></span><ChevronDown className={`h-5 w-5 shrink-0 text-primary transition-all duration-300 group-hover:text-primary ${membershipOpen?"rotate-180":""}`} /></button>{message&&<p className="rounded-full bg-accent px-3 py-1.5 text-xs text-primary">{message}</p>}</div>
      {membershipOpen?<><div className="flex justify-end border-t border-border px-4 pt-4"><ExportCsvButton filename="talepo-kullanicilar.csv" rows={users.map(user=>({"Ad soyad":user.name??"", "E-posta":user.email??"", "Üyelik no":user.membershipNumber, "Yetki":user.platformRole, "Plan":user.planTier??"", "Durum":user.status, "Son giriş":user.lastLoginAt??"", "Kayıt zamanı":user.createdAt}))}/></div><div className="grid gap-2 border-b border-border p-4 sm:grid-cols-[1fr_repeat(3,150px)_auto]"><div className="flex items-center gap-2 rounded-xl border border-border bg-muted px-3"><Search className="h-4 w-4 text-muted-foreground"/><input aria-label="Kullanıcı ara" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void search(1)}} placeholder={canSeeSensitive?"İsim, e-posta, telefon veya üye no":"İsim veya üye no"} className="w-full bg-transparent py-2.5 text-sm outline-none"/></div><select aria-label="Kullanıcı durumu filtresi" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-border bg-card px-3 text-xs"><option value="">Tüm durumlar</option><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Pasif</option></select><select aria-label="Platform rolü filtresi" value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-border bg-card px-3 text-xs"><option value="">Tüm roller</option><option value="USER">Kullanıcı</option><option value="SUPPORT">Destek</option><option value="MODERATOR">Moderatör</option><option value="ANALYST">Analist</option><option value="ADMIN">Admin</option>{canManageRoles?<option value="SUPER_ADMIN">Süper Admin</option>:null}</select>{canManageBilling?<select aria-label="Üyelik planı filtresi" value={plan} onChange={e=>setPlan(e.target.value)} className="rounded-xl border border-border bg-card px-3 text-xs"><option value="">Tüm planlar</option><option value="STANDARD">Bireysel</option><option value="PROFESSIONAL">Profesyonel</option></select>:<div className="flex items-center rounded-xl border border-border bg-muted px-3 text-xs text-muted-foreground">Plan bilgisi gizli</div>}<button onClick={()=>void search(1)} className="rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground">Ara</button></div>
      <div className="overflow-x-auto"><Table className="w-full min-w-[1120px] table-auto text-left text-sm"><TableHeader className="bg-muted text-[11px] uppercase tracking-[.12em] text-muted-foreground"><TableRow>{["Kullanıcı","Yetki","Plan","Durum","Son giriş","Bonus","İşlem"].map(x=><TableHead key={x} className={`px-3 py-4 font-semibold first:pl-5 ${x==="Kullanıcı"?"w-[24%]":x==="İşlem"?"w-[210px]":""}`}>{x}</TableHead>)}</TableRow></TableHeader><TableBody className="divide-y divide-border">{users.map(user=><TableRow key={user.id} className="hover:bg-accent">
        <TableCell className="px-6 py-4"><button disabled={!canSeeSensitive} onClick={canSeeSensitive?()=>void inspect(user.id):undefined} className="flex items-center gap-3 text-left disabled:cursor-default"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent font-semibold text-primary">{(user.name??user.email??"K")[0].toUpperCase()}</span><span><span className="flex items-center gap-2 font-semibold">{user.name??"İsimsiz kullanıcı"}{user.isAdmin&&<ShieldCheck className="h-4 w-4 text-amber-700"/>}</span><span className="mt-0.5 block text-xs text-muted-foreground">{user.email} · {user.membershipNumber}</span></span></button></TableCell>
        <TableCell className="px-4">{canEditRole(user)?<select value={user.platformRole} onChange={e=>update(user.id,{platformRole:e.target.value as AdminUser["platformRole"]})} className="rounded-xl border border-border bg-card px-3 py-2 text-xs"><option value="USER">Kullanıcı</option><option value="SUPPORT">Destek</option><option value="MODERATOR">Moderatör</option><option value="ANALYST">Analist</option>{canManageRoles?<><option value="ADMIN">Admin</option><option value="SUPER_ADMIN">Süper Admin</option></>:null}</select>:<span className="text-xs text-muted-foreground">{roleLabel(user.platformRole)}</span>}</TableCell>
        <TableCell className="px-4">{canManageBilling?<select value={user.planTier??"STANDARD"} onChange={e=>update(user.id,{planTier:e.target.value as NonNullable<AdminUser["planTier"]>})} className="rounded-xl border border-border bg-card px-3 py-2 text-xs"><option value="STANDARD">Bireysel</option><option value="PROFESSIONAL">Profesyonel</option></select>:canViewBilling?<div className="text-xs text-muted-foreground"><p>{user.planTier??"Bireysel"}</p><p className={user.billingStatus === "ACTIVE" ? "text-primary" : "text-amber-700"}>{billingStatusLabel(user.billingStatus)}{user.billingPeriodEnd ? ` · ${new Date(user.billingPeriodEnd).toLocaleDateString("tr-TR")}` : ""}</p></div>:<span className="text-xs text-muted-foreground">Gizli</span>}</TableCell>
        <TableCell className="px-4">{canManageUsers&&(canManageRoles||canEditRole(user)||user.platformRole==="USER")?<select value={user.status} onChange={e=>update(user.id,{status:e.target.value as AdminUser["status"]})} className="rounded-xl border border-border bg-card px-3 py-2 text-xs"><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Pasif</option></select>:<span className="text-xs text-muted-foreground">{user.status==="ACTIVE"?"Aktif":"Pasif"}</span>}</TableCell>
        <TableCell className="px-4 text-xs text-muted-foreground">{canSeeSensitive?dateTime(user.lastLoginAt):"Gizli"}</TableCell><TableCell className="px-4">{canManageBilling?<input type="number" min={0} max={10000} value={user.bonusOfferCredits} onChange={e=>update(user.id,{bonusOfferCredits:Number(e.target.value)})} className="w-20 rounded-xl border border-border bg-card px-3 py-2"/>:<span className="text-xs text-muted-foreground">Gizli</span>}</TableCell>
        <TableCell className="w-[210px] px-3"><div className="grid grid-cols-3 gap-1.5">{canSeeSensitive?<button onClick={()=>void inspect(user.id)} className="h-9 rounded-xl border border-border px-1.5 text-xs font-medium transition hover:border-primary/25 hover:bg-accent">İncele</button>:null}{canManageRoleNotes(user)?<button type="button" onClick={()=>setNotedUser(user)} className="h-9 rounded-xl border border-sky-200 px-1.5 text-xs font-medium text-sky-700 transition hover:border-sky-200 hover:bg-sky-50">Notlar</button>:null}{canManageRoles&&user.platformRole==="SUPER_ADMIN"&&user.id!==currentUserId?<button type="button" onClick={()=>setMfaResetUser(user)} className="h-9 rounded-xl border border-amber-200 px-1.5 text-xs font-medium text-amber-700 transition hover:border-amber-200 hover:bg-amber-50">MFA sıfırla</button>:null}{canManageUsers&&(canManageRoles||canEditRole(user)||user.platformRole==="USER")?<button onClick={()=>{setPendingSave(user);setReason("");}} disabled={busyId===user.id} className="inline-flex h-9 items-center justify-center gap-1 rounded-xl bg-primary px-1.5 text-xs font-bold text-primary-foreground shadow-sm shadow-emerald-300/10 transition hover:-translate-y-0.5 hover:bg-primary/90 active:translate-y-0 disabled:opacity-50">{busyId===user.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}Kaydet</button>:<span className="col-span-3 text-xs text-muted-foreground">Salt okunur</span>}</div></TableCell>
      </TableRow>)}</TableBody></Table></div>
      <div className="flex items-center justify-end gap-3 border-t border-border px-5 py-4"><button disabled={page<=1} onClick={()=>void search(page-1)} className="rounded-xl border border-border p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4"/></button><span className="text-xs text-muted-foreground">Sayfa {page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>void search(page+1)} className="rounded-xl border border-border p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4"/></button></div></>:null}
    </section>
    {(detailBusy||detail)&&<div className="fixed inset-0 z-[100] flex justify-end bg-black/60 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target){setDetail(null);setDetailBusy(false);}}}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-border bg-card p-6 shadow-2xl">{detailBusy?<div className="flex h-full items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary"/></div>:detail&&<><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-primary">Kullanıcı dosyası</p><h3 className="mt-2 text-2xl font-semibold">{detail.name??"İsimsiz kullanıcı"}</h3><p className="mt-1 text-sm text-muted-foreground">{detail.email} · {detail.membershipNumber}</p></div><button onClick={()=>setDetail(null)} className="rounded-xl border border-border p-2"><X className="h-5 w-5"/></button></div>
      <div className="mt-6 grid grid-cols-3 gap-3"><Stat icon={Clock3} label="Son giriş" value={dateTime(detail.lastLoginAt)}/><Stat icon={FileText} label="Talepler" value={String(detail._count.createdRequests)}/><Stat icon={HandCoins} label="Teklifler" value={String(detail._count.submittedOffers)}/></div>
      <div className="mt-6 flex gap-2 border-b border-border"><Tab active={tab==="info"} onClick={()=>setTab("info")}>Kayıt bilgileri</Tab><Tab active={tab==="history"} onClick={()=>setTab("history")}>Geçmiş hareketler</Tab></div>
      {tab==="info"?<div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Ad soyad",detail.name],["E-posta",detail.email],["Telefon",detail.phone],["Konum",[detail.district,detail.city,detail.country].filter(Boolean).join(", ")],["Kayıt yöntemi",detail.accounts.map(x=>x.provider).join(", ")||"Şifre"],["Kayıt zamanı",dateTime(detail.createdAt)],["E-posta doğrulama",dateTime(detail.emailVerified)],["Son güncelleme",dateTime(detail.updatedAt)]].map(([k,v])=><div key={k as string} className="rounded-2xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{k}</p><p className="mt-1 text-sm">{v||"Belirtilmemiş"}</p></div>)}{detail.biography&&<div className="sm:col-span-2 rounded-2xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Biyografi</p><p className="mt-2 text-sm leading-6">{detail.biography}</p></div>}</div>:<div className="mt-5 space-y-3"><div className="rounded-2xl border border-primary/25 bg-accent p-4"><p className="text-xs text-primary">Son giriş zamanı</p><p className="mt-1 font-semibold text-primary">{dateTime(detail.lastLoginAt)}</p></div>{detail.timeline?.map(item=><div key={item.id} className="relative ml-3 border-l border-border py-2 pl-6 before:absolute before:-left-1 before:top-5 before:h-2 before:w-2 before:rounded-full before:bg-primary"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{item.type}</p><p className="mt-1 text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{dateTime(item.occurredAt)}{item.meta?` · ${item.meta}`:""}</p></div>)}</div>}
      </>}</aside></div>}
    {pendingSave?<div className="fixed inset-0 z-[210] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.currentTarget===event.target)setPendingSave(null);}}><div role="dialog" aria-modal="true" aria-labelledby="admin-change-title" className="w-full max-w-lg rounded-xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-700">Denetimli işlem</p><h3 id="admin-change-title" className="mt-2 text-xl font-semibold">Değişiklik gerekçesi</h3><p className="mt-2 text-sm text-muted-foreground">{pendingSave.name??pendingSave.email} için yapılan işlem kalıcı denetim kaydına eklenecek.</p></div><button type="button" onClick={()=>setPendingSave(null)} className="rounded-xl border border-border p-2"><X className="h-4 w-4"/></button></div><textarea autoFocus value={reason} onChange={event=>setReason(event.target.value)} placeholder="Örn. Destek talebi doğrultusunda plan güncellendi" rows={4} className="mt-5 w-full resize-none rounded-2xl border border-border bg-muted p-4 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary/25"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setPendingSave(null)} className="rounded-xl border border-border px-4 py-2.5 text-sm text-muted-foreground">Vazgeç</button><button type="button" disabled={reason.trim().length<5} onClick={()=>{const target=pendingSave;const submittedReason=reason.trim();setPendingSave(null);void save(target,submittedReason);}} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-40">Kaydet ve kayıt oluştur</button></div></div></div>:null}
    {notedUser?<RoleUserNotesPanel user={{id:notedUser.id,label:notedUser.name??notedUser.email??"Kullanıcı",role:roleLabel(notedUser.platformRole)}} onClose={()=>setNotedUser(null)}/>:null}
    {mfaResetUser?<SuperAdminMfaReset user={{id:mfaResetUser.id,label:mfaResetUser.name??mfaResetUser.email??"Süper Admin"}} onClose={()=>setMfaResetUser(null)}/>:null}
  </>;
}
function Stat({icon:Icon,label,value}:{icon:typeof UserRound;label:string;value:string}){return <div className="rounded-2xl border border-border bg-card p-4"><Icon className="h-4 w-4 text-primary"/><p className="mt-3 text-[11px] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`border-b-2 px-3 py-3 text-sm ${active?"border-primary/25 text-primary":"border-transparent text-muted-foreground"}`}>{children}</button>}
function roleLabel(role:AdminUser["platformRole"]){return {USER:"Kullanıcı",SUPPORT:"Destek",MODERATOR:"Moderatör",ANALYST:"Analist",ADMIN:"Admin",SUPER_ADMIN:"Süper Admin"}[role]}
function billingStatusLabel(status:string|null){return {ACTIVE:"Ödeme aktif",PENDING:"Ödeme bekliyor",PAST_DUE:"Ödeme gecikmiş",CANCEL_AT_PERIOD_END:"Dönem sonunda kapanacak",CANCELED:"İptal edildi",EXPIRED:"Süresi doldu",INACTIVE:"Aktif ödeme yok"}[status??"INACTIVE"]??status}
