"use client";
import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { RefreshCw } from "lucide-react";

const metrics = { newUsers: "Yeni kullanıcı", companyRegistrations: "Firma kayıtları", companyClosures: "Firma kapatmaları", published: "Yayınlanan talep", offers: "Teklif", accepted: "Kabul edilen teklif", failedBilling: "Başarısız ödeme" };
type Metric = keyof typeof metrics; type Point = { date: string; [key: string]: number | string };
const subscribe = (callback: () => void) => { const fn = () => callback(); window.addEventListener("storage", fn); window.addEventListener("talepo-admin-trend-change", fn); return () => { window.removeEventListener("storage", fn); window.removeEventListener("talepo-admin-trend-change", fn); }; };
const readDays = (): 7 | 30 | 90 => { const value = localStorage.getItem("talepo-admin-trend-days"); return value === "7" || value === "90" ? Number(value) as 7 | 30 | 90 : 30; };
const readMetric = (): Metric => { const value = localStorage.getItem("talepo-admin-trend-metric"); return value && value in metrics ? value as Metric : "offers"; };
const store = (key: string, value: string) => { localStorage.setItem(key, value); window.dispatchEvent(new Event("talepo-admin-trend-change")); };

export function AdminChartInsights() {
  const storedDays = useSyncExternalStore(subscribe, readDays, () => 30 as 7 | 30 | 90); const storedMetric = useSyncExternalStore(subscribe, readMetric, () => "offers" as Metric);
  const [days, setDays] = useState<7 | 30 | 90>(storedDays); const [metric, setMetric] = useState<Metric>(storedMetric); const [points, setPoints] = useState<Point[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  const fetchInsights = useCallback(async (signal?: AbortSignal) => { try { const response = await fetch(`/api/admin/health?days=${days}`, { cache: "no-store", signal }); const value = await response.json(); if (!response.ok) throw new Error(value.message); if (!signal?.aborted) { setPoints(value.trend ?? []); setError(""); setBusy(false); } } catch (reason) { if (!signal?.aborted && (reason as DOMException).name !== "AbortError") { setError(reason instanceof Error ? reason.message : "Veriler alınamadı."); setBusy(false); } } }, [days]);
  const refreshInsights = useCallback(() => { setBusy(true); setError(""); void fetchInsights(); }, [fetchInsights]);
  useEffect(() => { const controller = new AbortController(); const task = Promise.resolve().then(() => fetchInsights(controller.signal)); return () => { void task; controller.abort(); }; }, [fetchInsights]);
  const values = useMemo(() => points.map(point => Number(point[metric] ?? 0)), [points, metric]); const total = values.reduce((a, b) => a + b, 0); const average = values.length ? Math.round(total / values.length * 10) / 10 : 0; const high = values.length ? Math.max(...values) : 0; const low = values.length ? Math.min(...values) : 0;
  const chooseDays = (value: 7 | 30 | 90) => { setBusy(true); setError(""); setDays(value); store("talepo-admin-trend-days", String(value)); }; const chooseMetric = (value: Metric) => { setMetric(value); store("talepo-admin-trend-metric", value); };
  return <section className="mt-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><select value={metric} onChange={event => chooseMetric(event.target.value as Metric)} className="rounded-xl border border-white/10 bg-[#102421] px-3 py-2 text-xs text-white">{Object.entries(metrics).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>{([7, 30, 90] as const).map(value => <button key={value} aria-pressed={days === value} onClick={() => chooseDays(value)} className={`rounded-xl px-3 py-2 text-xs ${days === value ? "bg-emerald-300 font-bold text-[#071310]" : "border border-white/10 text-white/55"}`}>{value} gün</button>)}</div><button onClick={refreshInsights} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs text-white/60"><RefreshCw className="h-3.5 w-3.5" />Yenile</button></div>{busy ? <div className="grid gap-3 sm:grid-cols-4">{[1, 2, 3, 4].map(i => <div key={i} className="h-20 animate-pulse rounded-2xl bg-white/[.06]" />)}</div> : error ? <div className="rounded-xl bg-rose-400/10 p-4 text-sm text-rose-200">{error}<button onClick={refreshInsights} className="ml-3 underline">Yeniden dene</button></div> : <div className="grid gap-3 sm:grid-cols-4"><Stat label={`Toplam ${metrics[metric]}`} value={total} /><Stat label="Günlük ortalama" value={average} /><Stat label="En yüksek" value={high} /><Stat label="En düşük" value={low} /></div>}</section>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><p className="text-xs text-white/40">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p></div>; }
