"use client";
import { useCallback, useEffect, useReducer, useState } from "react";
import Link from "next/link"; import { AlertTriangle, ArrowLeft, RefreshCw } from "lucide-react";
const labels: Record<string,string> = { newUsers:"Yeni kullanıcı", companyRegistrations:"Firma kayıtları", companyClosures:"Firma kapatmaları", published:"Yayınlanan talep", offers:"Teklif", accepted:"Kabul edilen teklif", acceptanceRate:"Kabul oranı", offerCoverage:"Teklif kapsaması", noOffer:"Teklifsiz talep", activeSellers:"Aktif satıcı", openCases:"Açık vaka", failedBilling:"Başarısız ödeme" };
type Data = { metrics: Record<string,number>; lastUpdatedAt: string }; type State = { status:"idle"|"loading"|"success"|"error"; data:Data|null; error:string }; type Action = { type:"loading" } | { type:"success"; data:Data } | { type:"error"; error:string };
const initial: State = { status:"idle", data:null, error:"" }; function reducer(state:State, action:Action):State { if(action.type === "loading") return { ...state, status:"loading", error:"" }; if(action.type === "success") return { status:"success", data:action.data, error:"" }; return { ...state, status:"error", error:action.error }; }
export function HealthCenter() { const [days,setDays] = useState<7|30|90>(30); const [state,dispatch] = useReducer(reducer,initial); const load = useCallback(async (signal?:AbortSignal) => { dispatch({type:"loading"}); try { const r=await fetch(`/api/admin/health?days=${days}`,{cache:"no-store",signal}); const value=await r.json(); if(!r.ok) throw new Error(value.message); dispatch({type:"success",data:value}); } catch(e) { if((e as DOMException).name !== "AbortError") dispatch({type:"error",error:e instanceof Error?e.message:"Veriler alınamadı."}); } },[days]); useEffect(()=>{const c=new AbortController(); const timer=window.setTimeout(()=>void load(c.signal),0); return()=>{window.clearTimeout(timer);c.abort();};},[load]); const data=state.data; const alerts=data?Object.entries(data.metrics).filter(([key,value])=>(key==="failedBilling"||key==="noOffer"||key==="companyClosures")&&value>0):[];
 return <main className="mx-auto max-w-7xl px-5 py-8 text-white sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/>Admin panele dön</Link><h1 className="mt-5 text-3xl font-semibold">Platform sağlığı</h1><p className="mt-2 text-sm text-white/45">Uyarıları ve tüm sağlık metriklerini buradan incele.</p></div><div className="flex gap-2">{([7,30,90] as const).map(value=><button key={value} onClick={()=>setDays(value)} className={`rounded-xl px-3 py-2 text-xs ${days===value?"bg-emerald-300 font-bold text-[#071310]":"border border-white/10 text-white/55"}`}>{value} gün</button>)}<button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-white/60"><RefreshCw className="h-3.5 w-3.5"/>Yenile</button></div></div>{state.status==="loading"||state.status==="idle"?<div className="mt-8 grid gap-3 sm:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-24 animate-pulse rounded-2xl bg-white/[.06]"/>)}</div>:state.status==="error"?<div className="mt-8 rounded-2xl bg-rose-400/10 p-5 text-sm text-rose-200">{state.error}</div>:data?<><section className={`mt-8 rounded-2xl border p-5 ${alerts.length?"border-amber-300/25 bg-amber-300/[.06]":"border-emerald-300/20 bg-emerald-300/[.05]"}`}><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-300"/><h2 className="font-semibold">{alerts.length?`${alerts.length} uyarı bulundu`:"Kritik uyarı yok"}</h2></div>{alerts.length?<ul className="mt-3 space-y-2 text-sm text-white/70">{alerts.map(([key,value])=><li key={key}>{labels[key]}: <strong>{value}</strong></li>)}</ul>:<p className="mt-2 text-sm text-white/50">İzlenen eşiklerde sorun görünmüyor.</p>}</section><section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Tüm metrikler</h2><span className="text-xs text-white/35">Son güncelleme: {new Date(data.lastUpdatedAt).toLocaleString("tr-TR")}</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.metrics).map(([key,value])=><div key={key} className="rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><p className="text-xs text-white/40">{labels[key]??key}</p><p className="mt-2 text-2xl font-semibold">{value}{key.includes("Rate")||key.includes("Coverage")?"%":""}</p><p className="mt-1 text-[11px] text-white/35">{alerts.some(([alertKey])=>alertKey===key)?"Uyarı eşiği aşıldı":"Normal"}</p></div>)}</div></section></>:null}</main>;
}
