"use client";

import Link from "next/link";
import { useState } from "react";

type Offer = { id: string; title: string | null; amount: string; status: string; createdAt: string; submittedBy: { id: string; name: string | null; email: string | null }; negotiations: Array<{ id: string; amount: string; status: string; proposedBySide: string; createdAt: string; respondedAt: string | null; proposedBy: { name: string | null; email: string | null } }>; conversation: { messages: Array<{ id: string; content: string | null; createdAt: string; sender: { name: string | null; email: string | null } }> } | null };
const statusLabels: Record<string, string> = { DRAFT: "Taslak", SUBMITTED: "Gönderildi", ACCEPTED: "Kabul edildi", REJECTED: "Reddedildi", WITHDRAWN: "Geri çekildi", COMPLETED: "Tamamlandı" };
const negotiationLabels: Record<string, string> = { PENDING: "Yanıt bekliyor", ACCEPTED: "Kabul edildi", REJECTED: "Reddedildi", CANCELLED: "İptal edildi", SUPERSEDED: "Yeni revize tutarla değiştirildi" };
const sideLabels: Record<string, string> = { BUYER: "Alıcı", SELLER: "Satıcı" };

export function RequestOffersDrawer({ requestTitle, offers }: { requestTitle: string; offers: Offer[] }) {
  const [open, setOpen] = useState(false);
  return <>
    <button type="button" onClick={() => offers.length && setOpen(true)} disabled={!offers.length} className={offers.length ? "cursor-pointer font-semibold text-primary underline-offset-4 hover:text-primary hover:underline" : "text-muted-foreground"}>{offers.length}</button>
    {open ? <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-label="Talep teklifleri"><button type="button" aria-label="Paneli kapat" onClick={() => setOpen(false)} className="absolute inset-0 cursor-pointer bg-black/60" /><aside className="absolute right-0 top-0 h-full w-full max-w-lg overflow-y-auto border-l border-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-primary">Talep teklifleri</p><h2 className="mt-2 text-2xl font-semibold">{requestTitle}</h2></div><button type="button" onClick={() => setOpen(false)} className="cursor-pointer rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-foreground" aria-label="Kapat">✕</button></div><div className="mt-6 grid gap-3">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div></aside></div> : null}
  </>;
}

function OfferCard({ offer }: { offer: Offer }) { const [historyOpen, setHistoryOpen] = useState(false); const messages = offer.conversation?.messages ?? []; return <div className="rounded-2xl border border-border bg-card p-4"><p className="font-semibold text-foreground">{offer.title ?? "Teklif"}</p><p className="mt-2 text-sm text-primary">İlk teklif: {offer.amount}</p><Link href={`/admin/users/${offer.submittedBy.id}`} className="mt-2 inline-block text-sm text-primary underline-offset-4 hover:underline">{offer.submittedBy.name ?? offer.submittedBy.email ?? "Teklif veren"}</Link><p className="mt-1 text-xs text-muted-foreground">{statusLabels[offer.status] ?? offer.status} · {offer.createdAt}</p><button type="button" onClick={() => setHistoryOpen((value) => !value)} className="mt-4 flex w-full cursor-pointer items-center justify-between border-t border-border pt-3 text-left text-sm font-medium text-foreground hover:text-foreground"><span>Teklif ve konuşma geçmişi</span><span>{historyOpen ? "−" : "+"}</span></button>{historyOpen ? <div className="mt-3 grid gap-2">{offer.negotiations.map((negotiation) => <div key={negotiation.id} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-amber-700">Pazarlık / Revize tutar</p><p className="mt-1 text-sm font-semibold text-amber-700">{negotiation.amount} · {sideLabels[negotiation.proposedBySide] ?? negotiation.proposedBySide}</p><p className="mt-1 text-xs text-muted-foreground">{negotiation.proposedBy.name ?? negotiation.proposedBy.email ?? "Kullanıcı"} · {negotiation.createdAt}</p><p className="mt-1 text-xs text-foreground">{negotiationLabels[negotiation.status] ?? negotiation.status}{negotiation.respondedAt ? ` · Yanıt: ${negotiation.respondedAt}` : ""}</p></div>)}{messages.map((message) => <div key={message.id} className="rounded-xl bg-muted p-3"><p className="text-xs text-primary">{message.sender.name ?? message.sender.email ?? "Kullanıcı"} · {message.createdAt}</p><p className="mt-1 whitespace-pre-wrap text-sm text-foreground">{message.content ?? "(İçerik yok)"}</p></div>)}{!offer.negotiations.length && !messages.length ? <p className="rounded-xl border border-dashed border-border p-3 text-sm text-muted-foreground">Henüz pazarlık veya konuşma geçmişi yok.</p> : null}</div> : null}</div>; }
