/** Approved 2026-09-06 subject/number/relationship regressions. Offline only. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { syncFromText, syncFromBrowse } from '../src/lib/request-composer/sync';
import { classifyNumbers, classifyModelTokenEvidence } from '../src/lib/request-understanding/number-role';
import { readRequestedTarget, readUsageContextSplit } from '../src/lib/request-understanding/part-relation';
const out=path.resolve(process.env.STRESS_SUBJECT_OUTPUT??'../../reports/qa-stress-fixes-2026-09-06/household');
const results:{name:string;passed:boolean;error?:string}[]=[];
function test(name:string,body:()=>void){try{body();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e)});}}
const parse=(text:string)=>syncFromText(null,text).state;
for(const text of ['24 parça yemek takımı arıyorum','6 kişilik 24 parça yemek takımı arıyorum','72 parça çatal bıçak takımı arıyorum'])test(`Set content is not a spare part: ${text}`,()=>{const s=parse(text);assert.equal(s.categoryId,'home-kitchen');assert.notEqual(s.understanding.requestSubject.kind.value,'PART');assert.match(s.lastComposedText??'',/takımı/iu);assert.equal(classifyModelTokenEvidence(text,/72/.test(text)?'72':'24'),'REJECTED');assert.ok(classifyNumbers(text).some(n=>String(n.role)==='PIECE_COUNT'));});
test('Real parts retain their role and quantity',()=>{const s=parse('Bosch çamaşır makinesi için 2 adet tahliye pompası arıyorum');assert.equal(s.understanding.requestSubject.kind.value,'PART');assert.equal(s.fields.quantity?.value,'2');assert.match(s.lastComposedText??'',/pompa/iu);});
test('Punctuated product keeps canonical identity and explicit soft answers',()=>{const raw='İndüksiyon uyumlu tencere takımı arıyorum';let s=parse(raw);for(const key of ['material','cookwareSize'])s=syncFromBrowse(s,{key,value:'Fark etmez',kind:'ANY',isAny:true}).state;const after=syncFromText(s,`${raw}. Ürün fotoğraflarını da görmek istiyorum.`).state;assert.match(String(after.fields.productType?.value),/tencere/iu);for(const key of ['material','cookwareSize'])assert.equal(after.fields[key]?.kind,'ANY');});
for(const text of ['380 V, 7.5 kW, 2 adet kompresör arıyorum. Bütçem 120000 TL.','Kompresor ariyorum, 220 volt olsun.'])test(`Compressor identity ends at request verb: ${text}`,()=>{const s=parse(text);assert.match(s.lastComposedText??'',/kompres[oö]r/iu);assert.doesNotMatch(String(s.fields.productType?.value??''),/arıyorum|ariyorum|bütçem|butcem|olsun/iu);assert.doesNotMatch(String(s.fields.model?.value??''),/arıyorum|ariyorum|olsun/iu);});
for(const text of ['Web tasarım hizmeti arıyorum.','Uzaktan web tasarım hizmeti arıyorum.','Yerinde web tasarım danışmanlığı arıyorum. Ankara.','Uzaktan yazılım geliştirme hizmeti arıyorum.'])test(`Service specialty preserved: ${text}`,()=>{const s=parse(text);const expected=/yazılım/iu.test(text)?/yazılım geliştirme/iu:/web tasarım/iu;assert.match(s.lastComposedText??'',expected);assert.match(String(s.understanding.requestSubject.serviceType?.value??s.understanding.requestSubject.name?.value??''),expected);});
for(const text of ['Bebek için 2 adet biberon ucu arıyorum','0-6 aylık bebek için 2 adet biberon ucu arıyorum'])test(`Quantity does not obscure usage target: ${text}`,()=>{const s=parse(text);assert.equal(readUsageContextSplit(text)?.role,'WHOLE_PRODUCT');assert.equal(readUsageContextSplit(text)?.target,'biberon ucu');assert.equal(s.fields.quantity?.value,'2');assert.match(String(s.fields.productType?.value),/biberon ucu/iu);});
test('Target quantity cleanup preserves raw source and genuine model digits',()=>{assert.equal(readRequestedTarget('2 adet biberon ucu arıyorum').raw,'2 adet biberon ucu arıyorum');assert.equal(readRequestedTarget('iPhone 15 arıyorum').value,'iPhone 15');assert.equal(readRequestedTarget('205/55 R16 lastik arıyorum').raw,'205/55 R16 lastik arıyorum');});
for(const [text,value]of [['Dört adet 205/55 R16 lastik arıyorum','4'],['Lastik arıyorum. Adet 2 olacak.','2'],['Üç adet lastik arıyorum','3']])test(`Quantity wording: ${text}`,()=>{const s=parse(text);assert.equal(s.fields.quantity?.value,value);assert.ok(classifyNumbers(text).some(n=>n.role==='QUANTITY'&&n.value===Number(value)));});
for(const text of ['500 m² satılık arsa arıyorum','500 m2 satılık arsa arıyorum'])test(`Area number role: ${text}`,()=>{assert.ok(classifyNumbers(text).some(n=>n.role==='AREA'&&n.value===500));const s=parse(text);assert.match(String(s.fields.area?.value??''),/500/);});
test('Phone replacement screen is a part',()=>{const s=parse('iPhone 15 için ekran arıyorum');assert.equal(s.understanding.requestSubject.kind.value,'PART');assert.match(s.lastComposedText??'',/ekran/iu);assert.notEqual(readUsageContextSplit('iPhone 15 için ekran arıyorum')?.role,'WHOLE_PRODUCT');});
test('Standalone monitor stays a whole product',()=>{const s=parse('Monitör arıyorum');assert.equal(s.understanding.requestSubject.kind.value,'PRODUCT');});
for(const text of ['Jeneratör yedek parçası arıyorum','Jeneratör için yedek parça arıyorum'])test(`Spare part retains catalog parent domain: ${text}`,()=>{const s=parse(text);assert.equal(s.categoryId,'machinery');assert.equal(s.understanding.requestSubject.kind.value,'PART');assert.match(s.lastComposedText??'',/jeneratör/iu);assert.match(s.lastComposedText??'',/parça/iu);});
test('Vehicle compatibility phrase separates the requested mirror',()=>{const s=parse('Honda Civic 2018 model aracıma uygun sol ayna arıyorum');assert.equal(s.categoryId,'automotive');assert.equal(s.fields.part?.value,'sol ayna');assert.equal(s.fields.brand?.value,'Honda');assert.equal(s.fields.model?.value,'Civic');assert.match(s.lastComposedText??'',/sol ayna/iu);});
test('Specific cleaning head keeps existing normalized service name',()=>{const s=parse('Ev temizliği arıyorum');assert.equal(s.understanding.requestSubject.serviceType?.value,'temizlik');});
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'subject-regressions.json'),JSON.stringify({generatedAt:new Date().toISOString(),passed:results.filter(r=>r.passed).length,total:results.length,results},null,2));console.log(JSON.stringify({passed:results.filter(r=>r.passed).length,total:results.length,failures:results.filter(r=>!r.passed)},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
