import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

export const ADMIN_MFA_COOKIE="talepo_admin_mfa";
const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const key=()=>createHmac("sha256",process.env.NEXTAUTH_SECRET||"talepo-dev-mfa").update("admin-mfa-v1").digest();
export function createMfaSecret(){const bytes=randomBytes(20);let bits="";for(const b of bytes)bits+=b.toString(2).padStart(8,"0");let out="";for(let i=0;i<bits.length;i+=5)out+=alphabet[parseInt(bits.slice(i,i+5).padEnd(5,"0"),2)];return out;}
function decodeBase32(value:string){let bits="";for(const char of value.replace(/=+$/g,"").toUpperCase()){const index=alphabet.indexOf(char);if(index>=0)bits+=index.toString(2).padStart(5,"0");}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes);}
function totp(secret:string,time=Date.now()){const counter=Math.floor(time/30000);const buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const digest=createHmac("sha1",decodeBase32(secret)).update(buf).digest();const offset=digest[digest.length-1]&15;return (((digest.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,"0"));}
export function verifyTotp(secret:string,code:string){const clean=code.replace(/\s/g,"");return [-1,0,1].some(step=>{const expected=Buffer.from(totp(secret,Date.now()+step*30000));const actual=Buffer.from(clean);return expected.length===actual.length&&timingSafeEqual(expected,actual);});}
export function encryptMfaSecret(secret:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const body=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${body.toString("base64url")}`;}
export function decryptMfaSecret(value:string){const [iv,tag,body]=value.split(".");const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(body,"base64url")),decipher.final()]).toString("utf8");}
export function createMfaSession(userId:string){const payload=Buffer.from(JSON.stringify({userId,exp:Date.now()+8*60*60*1000})).toString("base64url");const sig=createHmac("sha256",key()).update(payload).digest("base64url");return `${payload}.${sig}`;}
export function verifyMfaSession(token:string|undefined,userId:string){if(!token)return false;try{const [payload,sig]=token.split(".");const expected=createHmac("sha256",key()).update(payload).digest();const actual=Buffer.from(sig,"base64url");if(expected.length!==actual.length||!timingSafeEqual(expected,actual))return false;const parsed=JSON.parse(Buffer.from(payload,"base64url").toString("utf8")) as {userId:string;exp:number};return parsed.userId===userId&&parsed.exp>Date.now();}catch{return false;}}
export function assertMfaSession(request:Request,userId:string){const token=request.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(`${ADMIN_MFA_COOKIE}=`))?.slice(ADMIN_MFA_COOKIE.length+1);if(!verifyMfaSession(token,userId))throw new Error("ADMIN_MFA_REQUIRED");}
