/**
 * Synthetic supplier pool — no real company / PII.
 * categoryDbIds ≠ categorySlugs ≠ taxonomyNodeIds.
 */

import { buildSupplierCapabilityProfilePreserveIds } from "../supplier-capability-profile";
import type { SupplierCapabilityProfile } from "../types";
import { CAT } from "./ids";

export function syntheticSuppliers(): SupplierCapabilityProfile[] {
  const rows: Parameters<typeof buildSupplierCapabilityProfilePreserveIds>[0][] = [
    {
      companyId: "sup-baby-stroller",
      label: "Bebek Arabası Uzmanı",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      taxonomyNodeIds: [CAT.baby.taxStroller],
      products: ["bebek arabası", "bebek arabasi", "stroller"],
      brands: ["chicco", "cybex", "joie"],
      aliases: ["bebek arabası", "puset"],
      keywords: ["bebek", "çocuk"],
      cities: ["istanbul"],
      nationwide: true,
    },
    {
      companyId: "sup-baby-general",
      label: "Bebek Ürünleri",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      products: ["bebek bezi", "mama sandalyesi", "bebek arabası"],
      aliases: ["bebek", "bebek arabası"],
      keywords: ["bebek", "çocuk"],
      nationwide: true,
    },
    {
      companyId: "sup-chicco-dealer",
      label: "Chicco Bayi",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      brands: ["chicco"],
      brandCoverage: "exhaustive",
      products: ["bebek arabası"],
      productCoverage: "partial",
      brandModelPairs: [{ brand: "chicco", model: "stroller-pro" }],
      inventorySignals: [
        {
          brand: "chicco",
          product: "bebek arabası",
          categoryDbId: CAT.baby.dbId,
        },
      ],
      alertSignals: [
        {
          brands: ["chicco"],
          categoryDbIds: [CAT.baby.dbId],
          categorySlugs: [CAT.baby.slug],
        },
      ],
    },
    {
      companyId: "sup-cybex-dealer",
      label: "Cybex Bayi",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      brands: ["cybex"],
      brandCoverage: "exhaustive",
      products: ["bebek arabası", "oto koltuğu"],
      productCoverage: "partial",
    },
    {
      companyId: "sup-tv-arcelik",
      label: "Arçelik TV",
      categoryDbIds: [CAT.appliances.dbId, CAT.technology.dbId],
      categorySlugs: [CAT.appliances.slug, CAT.technology.slug],
      taxonomyNodeIds: [CAT.appliances.taxTv],
      products: ["televizyon", "tv"],
      productCoverage: "partial",
      brands: ["arçelik", "arcelik"],
      brandCoverage: "partial",
      models: ["a55"],
      modelCoverage: "partial",
      brandModelPairs: [{ brand: "arçelik", model: "a55" }],
      inventorySignals: [
        {
          brand: "arçelik",
          model: "a55",
          product: "televizyon",
          categoryDbId: CAT.appliances.dbId,
          taxonomyNodeId: CAT.appliances.taxTv,
        },
      ],
      keywords: ["inç", "ekran"],
    },
    {
      companyId: "sup-arcelik-appliance",
      label: "Arçelik Beyaz Eşya",
      categoryDbIds: [CAT.appliances.dbId],
      categorySlugs: [CAT.appliances.slug],
      taxonomyNodeIds: [CAT.appliances.taxWasher],
      products: ["çamaşır makinesi", "buzdolabı"],
      productCoverage: "exhaustive",
      brands: ["arçelik", "arcelik"],
      brandCoverage: "partial",
      keywords: ["beyaz eşya"],
    },
    {
      companyId: "sup-samsung-phone",
      label: "Samsung Telefon",
      categoryDbIds: [CAT.technology.dbId],
      categorySlugs: [CAT.technology.slug],
      brands: ["samsung"],
      brandCoverage: "exhaustive",
      models: ["galaxy a55", "a55"],
      modelCoverage: "exhaustive",
      brandModelPairs: [{ brand: "samsung", model: "a55" }],
      products: ["telefon", "smartphone"],
      productCoverage: "exhaustive",
    },
    {
      companyId: "sup-cartesian-a55",
      label: "Cartesian Brand Model Trap",
      categoryDbIds: [CAT.appliances.dbId],
      categorySlugs: [CAT.appliances.slug],
      brands: ["arçelik", "samsung"],
      models: ["a55"],
      brandCoverage: "partial",
      modelCoverage: "partial",
      products: ["televizyon"],
      productCoverage: "partial",
      // Intentionally NO brandModelPairs and NO inventory pair — cartesian only.
    },
    {
      companyId: "sup-tech-catalog-gap",
      label: "Genel Teknoloji",
      categoryDbIds: [CAT.technology.dbId],
      categorySlugs: [CAT.technology.slug],
      products: [],
      aliases: ["teknoloji", "elektronik"],
      keywords: ["teknoloji"],
      nationwide: true,
    },
    {
      companyId: "sup-print-parts",
      label: "Matbaa Yedek Parça",
      categoryDbIds: [CAT.printing.dbId, CAT.machinery.dbId],
      categorySlugs: [CAT.printing.slug, CAT.machinery.slug],
      taxonomyNodeIds: [CAT.printing.taxParts],
      products: ["nemlendirme pompası"],
      productCoverage: "exhaustive",
      brands: ["heidelberg"],
      brandCoverage: "partial",
      models: ["sm 74", "sm74"],
      modelCoverage: "partial",
      brandModelPairs: [{ brand: "heidelberg", model: "sm 74" }],
      aliases: ["nemlendirme", "dampening pump"],
      inventorySignals: [
        {
          brand: "heidelberg",
          model: "sm 74",
          product: "nemlendirme pompası",
          categoryDbId: CAT.printing.dbId,
          taxonomyNodeId: CAT.printing.taxParts,
        },
      ],
      keywords: ["matbaa", "baskı"],
    },
    {
      companyId: "sup-print-press",
      label: "Matbaa Makine",
      categoryDbIds: [CAT.printing.dbId, CAT.machinery.dbId],
      categorySlugs: [CAT.printing.slug, CAT.machinery.slug],
      taxonomyNodeIds: [CAT.machinery.taxPress],
      products: ["baskı makinesi", "offset"],
      productCoverage: "exhaustive",
      brands: ["heidelberg"],
      brandCoverage: "partial",
      models: ["sm 74"],
      modelCoverage: "partial",
      brandModelPairs: [{ brand: "heidelberg", model: "sm 74" }],
      aliases: ["heidelberg sm 74"],
      keywords: ["matbaa"],
    },
    {
      companyId: "sup-print-brochure",
      label: "Broşür Baskı",
      categoryDbIds: [CAT.printing.dbId],
      categorySlugs: [CAT.printing.slug],
      products: ["broşür", "brosur", "katalog"],
      productCoverage: "exhaustive",
      aliases: ["broşür baskı"],
      keywords: ["baskı", "offset"],
      nationwide: true,
    },
    {
      companyId: "sup-water-pump",
      label: "Genel Su Pompası",
      categoryDbIds: [CAT.machinery.dbId],
      categorySlugs: [CAT.machinery.slug],
      products: ["su pompası"],
      productCoverage: "exhaustive",
      aliases: ["su pompası"],
      keywords: ["su pompası"],
      excluded: { categorySlugs: [CAT.printing.slug], categoryDbIds: [CAT.printing.dbId] },
    },
    {
      companyId: "sup-re-istanbul",
      label: "İstanbul Emlak",
      categoryDbIds: [CAT.realEstate.dbId],
      categorySlugs: [CAT.realEstate.slug],
      taxonomyNodeIds: [CAT.realEstate.taxFlat],
      products: ["daire", "konut"],
      cities: ["istanbul"],
      districts: ["kadıköy", "besiktas", "beşiktaş"],
      keywords: ["kiralık", "satılık"],
    },
    {
      companyId: "sup-re-nationwide",
      label: "Türkiye Emlak",
      categoryDbIds: [CAT.realEstate.dbId],
      categorySlugs: [CAT.realEstate.slug],
      products: ["daire", "villa"],
      nationwide: true,
      aliases: ["emlak"],
    },
    {
      companyId: "sup-auto-clio",
      label: "Renault Clio",
      categoryDbIds: [CAT.automotive.dbId],
      categorySlugs: [CAT.automotive.slug],
      taxonomyNodeIds: [CAT.automotive.taxCar],
      products: ["otomobil", "araç"],
      productCoverage: "partial",
      brands: ["renault"],
      brandCoverage: "partial",
      models: ["clio"],
      modelCoverage: "partial",
      brandModelPairs: [{ brand: "renault", model: "clio", family: "clio" }],
      families: ["clio"],
      inventorySignals: [
        {
          brand: "renault",
          model: "clio",
          categoryDbId: CAT.automotive.dbId,
        },
      ],
    },
    {
      companyId: "sup-partial-brand-generalist",
      label: "Partial Brand List Generalist",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      brands: ["joie"],
      brandCoverage: "partial",
      products: ["bebek arabası"],
      productCoverage: "partial",
      // Chicco not listed — must NOT hard-drop on Chicco request.
    },
    {
      companyId: "sup-partial-product-catalog",
      label: "Partial Product Catalog",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      brands: [],
      brandCoverage: "unknown",
      products: ["mama sandalyesi"],
      productCoverage: "partial",
      // bebek arabası not listed — must NOT hard-drop; stay NEAR via category.
    },
    {
      companyId: "sup-exhaustive-brand-only",
      label: "Exhaustive Brand Only",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      brands: ["cybex"],
      brandCoverage: "exhaustive",
      products: ["bebek arabası"],
      productCoverage: "partial",
    },
    {
      companyId: "sup-explicit-exclude-chicco",
      label: "Explicit Exclude Chicco",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      products: ["bebek arabası"],
      productCoverage: "partial",
      brands: ["joie"],
      brandCoverage: "partial",
      excluded: { brands: ["chicco"] },
    },
    {
      companyId: "sup-model-unknown-product-expert",
      label: "Model Unknown Product Expert",
      categoryDbIds: [CAT.automotive.dbId],
      categorySlugs: [CAT.automotive.slug],
      products: ["otomobil"],
      productCoverage: "partial",
      brands: ["renault"],
      brandCoverage: "partial",
      models: [],
      modelCoverage: "unknown",
      // No Clio model knowledge — brand+model request should keep as NEAR via product/category.
    },
    {
      companyId: "sup-bosch-appliance",
      label: "Bosch Beyaz Eşya",
      categoryDbIds: [CAT.appliances.dbId],
      categorySlugs: [CAT.appliances.slug],
      taxonomyNodeIds: [CAT.appliances.taxWasher],
      brands: ["bosch"],
      brandCoverage: "partial",
      families: ["serie 6", "series 6"],
      products: ["çamaşır makinesi", "bulaşık makinesi"],
      productCoverage: "exhaustive",
      aliases: ["serie 6"],
    },
    {
      companyId: "sup-bosch-auto-service",
      label: "Bosch Otomotiv Servis",
      categoryDbIds: [CAT.automotive.dbId],
      categorySlugs: [CAT.automotive.slug],
      taxonomyNodeIds: [CAT.automotive.taxService],
      brands: ["bosch"],
      brandCoverage: "partial",
      products: ["fren balata", "enjektör"],
      productCoverage: "exhaustive",
      aliases: ["bosch car service"],
      keywords: ["otomotiv", "servis"],
    },
    {
      companyId: "sup-services-logo",
      label: "Logo Tasarım",
      categoryDbIds: [CAT.services.dbId],
      categorySlugs: [CAT.services.slug],
      taxonomyNodeIds: [CAT.services.taxDesign],
      products: ["logo tasarımı", "logo", "grafik tasarım"],
      aliases: ["logo", "branding"],
      nationwide: true,
      keywords: ["uzaktan", "remote"],
      availabilityCapability: true,
    },
    {
      companyId: "sup-furniture",
      label: "Mobilya",
      categoryDbIds: [CAT.furniture.dbId],
      categorySlugs: [CAT.furniture.slug],
      taxonomyNodeIds: [CAT.furniture.taxSofa],
      products: ["masa", "sandalye", "koltuk"],
      cities: ["ankara"],
    },
    {
      companyId: "sup-home-kitchen",
      label: "Ev Mutfak",
      categoryDbIds: [CAT.homeKitchen.dbId],
      categorySlugs: [CAT.homeKitchen.slug],
      products: ["tencere", "tava"],
      brands: ["tefal"],
    },
    {
      companyId: "sup-health",
      label: "Sağlık Ürün",
      categoryDbIds: [CAT.health.dbId],
      categorySlugs: [CAT.health.slug],
      products: ["tansiyon aleti"],
      aliases: ["sağlık"],
    },
    {
      companyId: "sup-wrong-cat-only",
      label: "Yanlış Kategori Tek",
      categoryDbIds: [CAT.services.dbId],
      categorySlugs: [CAT.services.slug],
      products: ["danışmanlık"],
      excluded: { brands: ["chicco"] },
    },
    {
      companyId: "sup-alias-collision-auto",
      label: "Pompa Otomotiv",
      categoryDbIds: [CAT.automotive.dbId],
      categorySlugs: [CAT.automotive.slug],
      products: ["yakıt pompası"],
      aliases: ["pompa"],
      keywords: ["otomotiv"],
    },
    {
      companyId: "sup-machinery-general",
      label: "Makine Genel",
      categoryDbIds: [CAT.machinery.dbId],
      categorySlugs: [CAT.machinery.slug],
      products: ["cnc", "pres"],
      nationwide: true,
    },
    {
      companyId: "sup-category-follow-only",
      label: "Yalnız Category Follow",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      alertSignals: [
        {
          categoryDbIds: [CAT.baby.dbId],
          categorySlugs: [CAT.baby.slug],
        },
      ],
    },
    {
      companyId: "sup-category-inventory-only",
      label: "Yalnız Category Inventory",
      categoryDbIds: [CAT.printing.dbId],
      categorySlugs: [CAT.printing.slug],
      inventorySignals: [{ categoryDbId: CAT.printing.dbId }],
    },
    {
      companyId: "sup-lexical-generic",
      label: "Genel Lexical",
      categoryDbIds: [CAT.services.dbId],
      categorySlugs: [CAT.services.slug],
      aliases: ["ürün", "makine", "servis", "araba"],
      keywords: ["ürün", "makine", "servis"],
    },
    {
      companyId: "sup-ac-hvac",
      label: "Klima HVAC",
      categoryDbIds: [CAT.appliances.dbId],
      categorySlugs: [CAT.appliances.slug],
      products: ["klima", "split klima"],
      aliases: ["klima"],
    },
    {
      companyId: "sup-auto-spare",
      label: "Oto Yedek Parça",
      categoryDbIds: [CAT.automotive.dbId],
      categorySlugs: [CAT.automotive.slug],
      products: ["yedek parça"],
      aliases: ["yedek parça"],
    },
    {
      companyId: "sup-multi-channel-same",
      label: "Çok Kanallı Tek Firma",
      categoryDbIds: [CAT.baby.dbId],
      categorySlugs: [CAT.baby.slug],
      taxonomyNodeIds: [CAT.baby.taxStroller],
      products: ["bebek arabası"],
      brands: ["joie"],
      aliases: ["bebek arabası"],
      inventorySignals: [
        {
          product: "bebek arabası",
          brand: "joie",
          categoryDbId: CAT.baby.dbId,
          taxonomyNodeId: CAT.baby.taxStroller,
        },
      ],
      alertSignals: [
        {
          categorySlugs: [CAT.baby.slug],
          products: ["bebek arabası"],
        },
      ],
    },
  ];

  return rows.map(buildSupplierCapabilityProfilePreserveIds);
}
