"use client";
import { useState } from "react";

export function ComplaintForm({ subjectType, subjectId, targetUserId }: { subjectType: "REQUEST" | "OFFER"; subjectId: string; targetUserId?: string | null }) {
  const [open, setOpen] = useState(false); const [summary, setSummary] = useState(""); const [details, setDetails] = useState(""); const [attachments, setAttachments] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const triggerLabel = subjectType === "OFFER" ? "Bu teklifle ilgili sorun bildir!" : "Bu taleple ilgili sorun bildir!";
  function selectFiles(event: React.ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []).slice(0, 3); files.forEach(file => { if (file.size > 700_000) return; const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") setAttachments(current => [...current, reader.result as string].slice(0, 3)); }; reader.readAsDataURL(file); }); }
  async function submit() { if (!summary.trim() || !details.trim()) return; setBusy(true); setMessage(null); try { const response = await fetch("/api/complaints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subjectType, subjectId, targetUserId, summary, details, attachmentUrls: attachments }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setMessage(`Şikayetiniz oluşturuldu. Takip kodu: ŞK-${data.complaintNumber}`); setSummary(""); setDetails(""); setAttachments([]); setOpen(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Şikayet oluşturulamadı."); } finally { setBusy(false); } }
  return <section className="mt-4 text-center"><div className="group flex items-center gap-2"><span className="h-px flex-1 origin-right bg-teal-700/35 transition-all duration-600 ease-out group-hover:translate-x-3 group-hover:scale-x-0 group-hover:opacity-0"/><button type="button" onClick={() => setOpen((value) => !value)} className="shrink-0 rounded-full border border-transparent px-3 py-1.5 text-xs font-medium text-black/40 transition-all duration-600 ease-out group-hover:border-teal-700/45 group-hover:bg-[#eef8f5] group-hover:px-4 group-hover:text-teal-800 group-hover:shadow-[0_3px_10px_rgba(13,110,101,0.12)]">{triggerLabel}</button><span className="h-px flex-1 origin-left bg-teal-700/35 transition-all duration-600 ease-out group-hover:-translate-x-3 group-hover:scale-x-0 group-hover:opacity-0"/></div>{open ? <div className="mx-auto mt-3 grid max-w-md gap-3 rounded-2xl border border-black/[0.08] bg-white p-4 text-left shadow-[0_12px_30px_rgba(15,31,29,0.08)]"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-[#0f1f1d]">Sorun bildir</p><button type="button" onClick={() => setOpen(false)} className="text-xs text-black/40 hover:text-black">Kapat</button></div><input value={summary} onChange={event => setSummary(event.target.value)} placeholder="Kısa başlık" className="rounded-xl border border-black/[0.1] bg-white px-3 py-2.5 text-sm text-black" /><textarea value={details} onChange={event => setDetails(event.target.value)} placeholder="Sorunu kısaca anlatın" rows={3} className="rounded-xl border border-black/[0.1] bg-white px-3 py-2.5 text-sm text-black" /><div><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-black/[0.1] bg-[#fafcfb] px-3 py-2 text-xs font-semibold text-teal-800 transition hover:bg-[#eef8f5]"><span aria-hidden="true">＋</span> Fotoğraf ekle<input type="file" accept="image/*" multiple onChange={selectFiles} className="sr-only" /></label><span className="ml-2 text-xs text-black/40">{attachments.length ? `${attachments.length} eklendi` : "En fazla 3"}</span></div><button type="button" disabled={busy || !summary.trim() || !details.trim()} onClick={() => void submit()} className="rounded-xl bg-teal-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Gönderiliyor…" : "Bildirimi gönder"}</button></div> : null}{message ? <p className="mt-2 text-sm font-medium text-teal-800">{message}</p> : null}</section>;
}
