import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requirePlatformAdmin } from "@/server/auth/require-platform-admin";
import { writeAdminAudit } from "@/server/admin/audit";

const STATUSES=["OPEN","INVESTIGATING","RESOLVED","DISMISSED"] as const; const PRIORITIES=["LOW","MEDIUM","HIGH","CRITICAL"] as const;
export async function GET(request:Request){try{await requirePlatformAdmin("moderation.view");const u=new URL(request.url);const status=u.searchParams.get("status");const items=await prisma.moderationCase.findMany({where:status&&STATUSES.includes(status as typeof STATUSES[number])?{status:status as typeof STATUSES[number]}:{},orderBy:[{priority:"desc"},{createdAt:"desc"}],take:100,select:{id:true,subjectType:true,subjectId:true,category:true,summary:true,priority:true,status:true,resolutionNote:true,createdAt:true,updatedAt:true,assignee:{select:{id:true,name:true,email:true}},reporter:{select:{id:true,name:true,email:true}}}});return NextResponse.json({ok:true,items:items.map(x=>({...x,createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString()}))});}catch(error){console.error("[admin/moderation]",error);return NextResponse.json({ok:false,message:"Moderasyon kayıtları alınamadı."},{status:403});}}
export async function POST(request:Request){try{const admin=await requirePlatformAdmin("moderation.manage");const b=await request.json() as {subjectType?:string;subjectId?:string;category?:string;summary?:string;priority?:string};if(!b.subjectType||!b.subjectId||!b.category||!b.summary?.trim())return NextResponse.json({ok:false,message:"Konu, kategori ve açıklama zorunlu."},{status:400});const priority=PRIORITIES.includes(b.priority as typeof PRIORITIES[number])?b.priority as typeof PRIORITIES[number]:"MEDIUM";const item=await prisma.$transaction(async tx=>{const created=await tx.moderationCase.create({data:{subjectType:b.subjectType!,subjectId:b.subjectId!,category:b.category!,summary:b.summary!.trim(),priority,reporterId:admin.id,assigneeId:admin.id}});await writeAdminAudit(tx,{actorId:admin.id,action:"MODERATION_CASE_CREATED",reason:b.summary!,metadata:{caseId:created.id,subjectType:created.subjectType,subjectId:created.subjectId},request});return created;});return NextResponse.json({ok:true,item});}catch(error){console.error("[admin/moderation]",error);return NextResponse.json({ok:false,message:"Moderasyon kaydı oluşturulamadı."},{status:403});}}
export async function PATCH(request:Request){try{const admin=await requirePlatformAdmin("moderation.manage");const b=await request.json() as {id?:string;status?:string;priority?:string;resolutionNote?:string};if(!b.id)return NextResponse.json({ok:false,message:"Kayıt seçilmedi."},{status:400});const current=await prisma.moderationCase.findUnique({where:{id:b.id}});if(!current)return NextResponse.json({ok:false,message:"Kayıt bulunamadı."},{status:404});const status=STATUSES.includes(b.status as typeof STATUSES[number])?b.status as typeof STATUSES[number]:current.status;const priority=PRIORITIES.includes(b.priority as typeof PRIORITIES[number])?b.priority as typeof PRIORITIES[number]:current.priority;const item=await prisma.$transaction(async tx=>{const updated=await tx.moderationCase.update({where:{id:b.id},data:{status,priority,resolutionNote:b.resolutionNote?.trim()||null,assigneeId:admin.id,resolvedAt:["RESOLVED","DISMISSED"].includes(status)?new Date():null}});await writeAdminAudit(tx,{actorId:admin.id,action:"MODERATION_CASE_UPDATED",reason:b.resolutionNote?.trim()||`Moderasyon durumu ${status} olarak güncellendi`,before:{status:current.status,priority:current.priority},after:{status,priority},metadata:{caseId:current.id},request});return updated;});return NextResponse.json({ok:true,item});}catch(error){console.error("[admin/moderation]",error);return NextResponse.json({ok:false,message:"Moderasyon kaydı güncellenemedi."},{status:403});}}
